name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run:  ls day* -d | xargs -I {} bash -c "cd '{}' && cargo clippy -- -W clippy::pedantic"
    - name: Build
      run:  ls day* -d | xargs -I {} bash -c "cd '{}' && cargo run"
    - name: Run tests
      run: ls day* -d | xargs -I {} bash -c "cd '{}' && cargo test"
